# Generated by Django 5.2.5 on 2025-10-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0007_subtask_owner_task_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['created_at'], 'permissions': [('can_subtask_owner', 'Can Subtask owner')], 'verbose_name': 'Подзадача', 'verbose_name_plural': 'Подзадачи'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'permissions': [('can_task_owner', 'Can Task owner')], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
